### ISSUE TITLE
App not loading map

### ISSUE THREAD

**Issue by Bram94** [rk234/RadarViewer#6]
Hi,

I am trying to test the app, but on running I only see the basic html page, as shown in this image: 
![image](https://github.com/rk234/RadarViewer/assets/24604991/1e8ebd09-bbb9-4a01-85be-69877affafb5)

I suppose the right side of the window should show a radar map, but this doesn't happen. Would you know what goes wrong here?

This is my command line: 
![image](https://github.com/rk234/RadarViewer/assets/24604991/31106580-e748-4ccf-8d30-d4a5159e2d6c)

**Comment by rk234** [comment]
Hello,

Sorry for the inconvenience. It's been a while since I've actively worked on RadarViewer - it's still in an early stage with many features missing and potential bugs. I am in the process of rewriting the app in kotlin for better performance and maintainability. As for your issue, the output in your command line seems to indicate it's an issue with hardware/gpu acceleration since RadarViewer utilizes WebGL and your gpu to render the radar data efficiently. Unfortunately, this isn't something that I can fix directly, but hopefully that gives you enough of a lead. Also if you're looking for a good NEXRAD level 2 radar viewer, I would recommend checking out [atticradar](https://atticradar.steepatticstairs.net), just note that it's not open source.

**Comment by Bram94** [comment]
Thanks for your response. 

But the GL error somehow only appears about a minute after starting the app, and search results for this error seem to indicate that it shouldn't actually prevent the app from rendering. So the issue is probably something else.

But indeed, there are alternatives that I can look at. So I'm definitely not in urgent need of a solution, and you should feel free to ignore this issue if you prefer.
